version: "3.9"

services:
  telegram_chanel_manager_bot:
    build: .
    image: telegram_chanel_manager_bot:2.2
    container_name: telegram_chanel_manager_bot
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./config.json:/app/config.json
      - ./data:/app/data
      - ./sessions:/app/sessions
      - ./backups:/app/backups
      - ./logs:/app/logs
    ports:
      - "1009:8000"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
