services:
  telegram_mediachanel_manager_bot:
    build: .
    image: telegram_mediachanel_manager_bot:4.0
    container_name: telegram_mediachanel_manager_bot
    restart: always
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      - ./.env
    volumes:
      - ./config.json:/app/config.json
      - ./data:/app/data
      - ./sessions:/app/sessions
      - ./backups:/app/backups
    ports:
      - "1009:8000"
    environment:
      - LOG_LEVEL=INFO
